---

- name: copy artifact
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    mode: 0400


# - name: extract artifact
#   become: yes
#   shell: tar -vxf artifact.tar.gz
- name: extract artifact.tar
  become: yes
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/
    remote_src: yes
    mode: 0400

- name: Install packages based on package.json.
  npm:
    path: ~/backend

# - name: "stop"
#   become: true
#   command: pm2 stop default
#   args:
#     chdir: /home/ubuntu/backend

# - name: Change the working directory to app/udapeople and start the app
#   command: pm2 start npm -- start
#   become: yes
#   args:
#     chdir: /home/ubuntu/backend

- name: start app
  become: yes
  shell: |
    cd backend
    pm2 stop default
    pm2 start npm -- start