---

- name: copy artifact
  become: yes
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz
    mode: 0755


# - name: extract artifact
#   become: yes
#   shell: tar -vxf artifact.tar.gz
- name: extract artifact.tar
  become: yes
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/
    remote_src: yes
    mode: 0755

- name: Install packages based on package.json.
  npm:
    path: ~/backend

- name: start app
  become: yes
  shell: |
    cd backend
    pm2 stop default
    pm2 start npm -- start