---

- name: copy artifact
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
    mode: 0400

- name: extract artifact.tar
  become: yes
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: yes
    mode: 0400

- name: Install packages based on package.json.
  npm:
    path: /home/ubuntu/backend

- name: "stop"
  become: true
  command: pm2 stop default
  args:
    chdir: /home/ubuntu/backend

- name: Change the working directory to app/udapeople and start the app
  command: pm2 start npm -- start
  become: yes
  args:
    chdir: /home/ubuntu/backend